# fly.toml app configuration file generated for feed-generator-be on 2023-07-24T11:06:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "feed-generator-be"
primary_region = "waw"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  # Whichever port you want to run this on
  FEEDGEN_PORT=3000
  # Change this to use a different bind address
  FEEDGEN_LISTENHOST="0.0.0.0"
  # Set to something like db.sqlite to store persistently
  FEEDGEN_SQLITE_LOCATION="/data/feed.db"
  # Don't change unless you're working in a different environment than the primary Bluesky network
  FEEDGEN_SUBSCRIPTION_ENDPOINT="wss://bsky.social"
  # Set this to the hostname that you intend to run the service at
  FEEDGEN_HOSTNAME="feed-generator-be.fly.dev"
  # Set this to the DID of the account you'll use to publish the feed
  # You can find your accounts DID by going to
  # https://bsky.social/xrpc/com.atproto.identity.resolveHandle?handle=${YOUR_HANDLE}
  FEEDGEN_PUBLISHER_DID="did:plc:e6pa2j5l6bvk3uqoup6mnste"
  # Delay between reconnect attempts to the firehose subscription endpoint (in milliseconds)
  FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY=3000
